import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Minimalist Desk Lamp",
    description: "A sleek, adjustable desk lamp with warm lighting for your workspace.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home Office",
  },
  {
    id: "2",
    name: "Wireless Earbuds",
    description: "Premium wireless earbuds with noise cancellation and long battery life.",
    price: 89.99,
    originalPrice: 129.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    sale: true,
  },
  {
    id: "3",
    name: "Leather Wallet",
    description: "Handcrafted genuine leather wallet with RFID protection.",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
  },
  {
    id: "4",
    name: "Smart Water Bottle",
    description: "Track your hydration with this smart water bottle that syncs with your phone.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Health",
  },
  {
    id: "5",
    name: "Ceramic Plant Pot",
    description: "Modern ceramic pot perfect for small indoor plants and succulents.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home Decor",
  },
  {
    id: "6",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof bluetooth speaker with 20 hours of battery life.",
    price: 59.99,
    originalPrice: 79.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    sale: true,
  },
  {
    id: "7",
    name: "Cotton Throw Blanket",
    description: "Soft, lightweight cotton blanket perfect for any season.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home Decor",
  },
  {
    id: "8",
    name: "Stainless Steel Water Bottle",
    description: "Double-walled insulated bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 19.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
  },
]
